#Requires -Version 5.1
<#
.SYNOPSIS
    Create a .venv inside the KiCad plugin directory, install kcaa from PyPI,
    and download the freerouting JAR for the auto-router feature.

.DESCRIPTION
    Run this script from inside the kicad_ai_assistant plugin folder, e.g.:

        cd "$env:APPDATA\kicad\10.0\scripting\plugins\kicad_ai_assistant"
        .\setup_plugin.ps1
#>

$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
$PythonVersion     = '3.13'
$FreroutingVersion = '2.2.3'
$JarName           = "freerouting-${FreroutingVersion}.jar"
$DownloadUrl       = "https://github.com/freerouting/freerouting/releases/download/v${FreroutingVersion}/${JarName}"

# $PSScriptRoot is the directory containing this script (the plugin folder).
$PluginDir = $PSScriptRoot
$VenvDir   = Join-Path $PluginDir '.venv'

# ---------------------------------------------------------------------------
# Read kcaa version from VERSION file (generated by Makefile from pyproject.toml)
# ---------------------------------------------------------------------------
$VersionFile = Join-Path $PluginDir 'VERSION'
if (-not (Test-Path $VersionFile)) {
    Write-Host "ERROR: VERSION file not found at $VersionFile"
    Write-Host "The VERSION file is generated by 'make dist-plugin' from pyproject.toml."
    exit 1
}
$KcaaVersion = (Get-Content $VersionFile -Raw).Trim()
Write-Host "kcaa version: $KcaaVersion (from VERSION file)"

# ---------------------------------------------------------------------------
# Sanity checks
# ---------------------------------------------------------------------------
if (-not (Get-Command 'uv' -ErrorAction SilentlyContinue)) {
    Write-Host "ERROR: uv not found in PATH. Install it from https://github.com/astral-sh/uv"
    exit 1
}

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
Write-Host "Plugin dir : $PluginDir"
Write-Host "Venv dir   : $VenvDir"
Write-Host ""

# ---------------------------------------------------------------------------
# Step 1/3 — Create / update the venv
# ---------------------------------------------------------------------------
Write-Host "Step 1/3 - Creating virtual environment ..."
uv venv "$VenvDir" --python $PythonVersion
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: uv venv failed (exit code $LASTEXITCODE)."
    exit $LASTEXITCODE
}

# ---------------------------------------------------------------------------
# Step 2/3 — Install kcaa from PyPI
# ---------------------------------------------------------------------------
Write-Host "Step 2/3 - Installing kcaa from PyPI ..."
uv pip install "kcaa==${KcaaVersion}" --python "$VenvDir"
uv pip install "pymupdf" --python "$VenvDir"
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: uv pip install failed (exit code $LASTEXITCODE)."
    exit $LASTEXITCODE
}

# ---------------------------------------------------------------------------
# Step 3/4 — Detect KiCad configuration
# ---------------------------------------------------------------------------
Write-Host ""
Write-Host "Step 3/3 - Downloading freerouting JAR ..."
$JarDest = Join-Path $PluginDir $JarName

if (Test-Path $JarDest) {
    Write-Host "  Already present: $JarDest (skipping download)"
} else {
    Write-Host "  URL: $DownloadUrl"
    try {
        Invoke-WebRequest -Uri $DownloadUrl -OutFile $JarDest -UseBasicParsing
        Write-Host "  Saved to: $JarDest"
    } catch {
        Write-Host "ERROR: Failed to download freerouting JAR: $_"
        exit 1
    }
}

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
Write-Host ""
Write-Host "Done! The plugin venv is ready at:"
Write-Host "  $(Join-Path $VenvDir 'Scripts\python.exe')"
Write-Host ""
Write-Host "Restart KiCad (or reload the plugin) for the changes to take effect."
