#!/usr/bin/env bash
# setup_plugin.sh — Create a .venv inside the KiCad plugin directory,
# install kcaa from PyPI, and download the freerouting JAR for the
# auto-router feature.
#
# Run this script from inside the kicad_ai_assistant plugin folder:
#
#   cd ~/.local/share/kicad/10.0/scripting/plugins/kicad_ai_assistant
#   ./setup_plugin.sh

set -euo pipefail

PYTHON_VERSION="3.13"
FREEROUTING_VERSION="2.2.3"
FREEROUTING_JAR="freerouting-${FREEROUTING_VERSION}.jar"
FREEROUTING_URL="https://github.com/freerouting/freerouting/releases/download/v${FREEROUTING_VERSION}/${FREEROUTING_JAR}"

# ---------------------------------------------------------------------------
# Resolve paths
# ---------------------------------------------------------------------------
# The script lives inside the plugin directory.
PLUGIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$PLUGIN_DIR/.venv"

# ---------------------------------------------------------------------------
# Read kcaa version from VERSION file (generated by Makefile from pyproject.toml)
# ---------------------------------------------------------------------------
VERSION_FILE="$PLUGIN_DIR/VERSION"
if [[ -f "$VERSION_FILE" ]]; then
    KCAA_VERSION="$(cat "$VERSION_FILE" | tr -d '[:space:]')"
    echo "kcaa version: $KCAA_VERSION (from VERSION file)"
else
    echo "ERROR: VERSION file not found at $VERSION_FILE"
    echo "The VERSION file is generated by 'make dist-plugin' from pyproject.toml."
    exit 1
fi

# ---------------------------------------------------------------------------
# Sanity checks
# ---------------------------------------------------------------------------
if ! command -v uv &>/dev/null; then
    echo "ERROR: uv not found in PATH. Install it from https://github.com/astral-sh/uv"
    exit 1
fi

if ! command -v curl &>/dev/null && ! command -v wget &>/dev/null; then
    echo "ERROR: curl or wget is required to download freerouting. Please install one."
    exit 1
fi

# ---------------------------------------------------------------------------
# Create / update the venv
# ---------------------------------------------------------------------------
echo "Plugin dir : $PLUGIN_DIR"
echo "Venv dir   : $VENV_DIR"
echo ""

echo "Step 1/3 — Creating virtual environment ..."
uv venv "$VENV_DIR" --python "$PYTHON_VERSION"

echo "Step 2/3 — Installing kcaa from PyPI ..."
uv pip install "kcaa==${KCAA_VERSION}" --python "$VENV_DIR"
uv pip install "pymupdf" --python "$VENV_DIR"

echo ""
echo "Step 3/3 — Downloading freerouting JAR ..."
FREEROUTING_DEST="$PLUGIN_DIR/$FREEROUTING_JAR"
if [[ -f "$FREEROUTING_DEST" ]]; then
    echo "  Already present: $FREEROUTING_DEST (skipping download)"
else
    echo "  URL: $FREEROUTING_URL"
    if command -v curl &>/dev/null; then
        curl -fL --progress-bar -o "$FREEROUTING_DEST" "$FREEROUTING_URL"
    else
        wget -q --show-progress -O "$FREEROUTING_DEST" "$FREEROUTING_URL"
    fi
    echo "  Saved to: $FREEROUTING_DEST"
fi

echo ""
echo "Done! The plugin venv is ready at:"
echo "  $VENV_DIR/bin/python"
echo ""
echo "Restart KiCad (or reload the plugin) for the changes to take effect."
